version: '3'
services:
  anonymouschat:
    image: alucio/anonymouschat:latest
    ports:
      - "${HOST_PORT:-80}:${CONTAINER_PORT:-3000}"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - ANONYMOUSCHAT_WEB_ENDPOINT=${ANONYMOUSCHAT_WEB_ENDPOINT}
      - ANONYMOUSCHAT_API_BASE_URL=${ANONYMOUSCHAT_API_BASE_URL}
      - ANONYMOUSCHAT_CLIENT_ID=${ANONYMOUSCHAT_CLIENT_ID}
      - ANONYMOUSCHAT_CLIENT_SECRET=${ANONYMOUSCHAT_CLIENT_SECRET}
      - ANONYMOUSCHAT_SHARABLE_URL=${ANONYMOUSCHAT_SHARABLE_URL}
      - ANONYMOUSCHAT_MANAGER_SLACK_ID=${ANONYMOUSCHAT_MANAGER_SLACK_ID}
      - ANONYMOUSCHAT_TABLENAME_PREFIX=${ANONYMOUSCHAT_TABLENAME_PREFIX}
      - ANONYMOUSCHAT_ENV=${ANONYMOUSCHAT_ENV}
      - ANONYMOUSCHAT_SLASH_COMMAND=${ANONYMOUSCHAT_SLASH_COMMAND}
      - ANONYMOUSCHAT_APP_NAME=${ANONYMOUSCHAT_APP_NAME}
      - ANONYMOUSCHAT_REDIRECT_HTTP_TO_HTTPS=${ANONYMOUSCHAT_REDIRECT_HTTP_TO_HTTPS}
      - ANONYMOUSCHAT_TOKEN_REFRESH_PASSWORD=${ANONYMOUSCHAT_TOKEN_REFRESH_PASSWORD}
      - ANONYMOUSCHAT_LOGLEVEL=${ANONYMOUSCHAT_LOGLEVEL}

